# Generated by Django 3.2.8 on 2022-05-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField(null=True, verbose_name='descripcion')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='static/core/img', verbose_name='imagen')),
            ],
        ),
    ]
